# Generated by Django 5.2 on 2025-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0002_alter_user_details_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('Admin', 'Admin')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
