# Generated by Django 5.2 on 2025-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0003_user_details_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Mechanic', 'Mechanic'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
