# Generated by Django 5.2 on 2025-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0004_alter_user_details_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='account_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
