# Generated by Django 5.2 on 2025-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0005_user_details_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='identification_proof',
            field=models.FileField(blank=True, null=True, upload_to='members/static/Files/identification_proofs/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/static/Images/users/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='members/static/Files/resumes/'),
        ),
    ]
