# Generated by Django 5.2 on 2025-04-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requests', '0001_initial'),
        ('User_Details', '0004_alter_user_details_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_History',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal')], max_length=15)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_gateway_response', models.TextField(blank=True, null=True)),
                ('payment_gateway_error', models.TextField(blank=True, null=True)),
                ('payment_gateway_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_gateway_authorization_code', models.CharField(blank=True, max_length=200, null=True)),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.rent_requests')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.service_requests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
            ],
        ),
    ]
