# Generated by Django 5.2 on 2025-04-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
        ('Requests', '0005_alter_sell_requests_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_history',
            name='rent_id',
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Requests.service_requests'),
        ),
    ]
