# Generated by Django 5.2 on 2025-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_remove_payment_history_rent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_history',
            name='payment_amount',
            field=models.FloatField(),
        ),
    ]
