# Generated by Django 5.2 on 2025-04-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Details', '0004_alter_user_details_role'),
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('rent_payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], max_length=50)),
                ('rent_end_date_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renter_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_to', to='User_Details.user_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
                ('vehicle_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.rent_vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_model_year', models.IntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_used_condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_proof_image', models.ImageField(upload_to='members/static/images/vehicle_proof_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('seller_identification_proof', models.ImageField(blank=True, null=True, upload_to='members/static/images/seller_identification_proofs/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('seller_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_details', to='User_Details.user_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], max_length=50)),
                ('buyer_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_details', to='User_Details.user_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
                ('vehicle_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.sell_requests')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request_type', models.CharField(choices=[('Full Vehicle Diagnostic', 'Full Vehicle Diagnostic'), ('Routine Maintenance Service', 'Routine Maintenance Service'), ('Car Wash & Vacuuming', 'Car Wash & Vacuuming'), ('Paint Protection & Polishing', 'Paint Protection & Polishing'), ('Tyre Replacement & Oil Change', 'Tyre Replacement & Oil Change')], max_length=50)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_proof_image', models.ImageField(upload_to='members/static/images/vehicle_proof_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('problem_description', models.TextField()),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='User_Details.user_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
            ],
        ),
    ]
