# Generated by Django 5.2 on 2025-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_requests',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
