# Generated by Django 5.2 on 2025-04-23 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_service_requests_service_date'),
        ('User_Details', '0004_alter_user_details_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_requests',
            name='total_hours_rented',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent_requests',
            name='rent_end_date_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rent_requests',
            name='renter_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_to', to='User_Details.user_details'),
        ),
    ]
