# Generated by Django 5.2 on 2025-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0003_rent_requests_total_hours_rented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_requests',
            name='branch',
            field=models.CharField(choices=[('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Ranip, Ahmedabad', 'Ranip, Ahmedabad'), ('Thaltej, Ahmedabad', 'Thaltej, Ahmedabad'), ('Mahesana', 'Mahesana')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_requests',
            name='vehicle_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/static/images/vehicle_proof_images/'),
        ),
    ]
