# Generated by Django 5.2 on 2025-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_service_requests_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_requests',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
