# Generated by Django 5.2 on 2025-04-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_model_year', models.IntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_proof_image', models.ImageField(upload_to='members/static/images/vehicle_proof_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented_currently', 'Rented_currently'), ('In_Service', 'In_Service')], max_length=20)),
            ],
        ),
    ]
