# Generated by Django 5.2 on 2025-04-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_vehicles',
            old_name='vehicle_price_per_day',
            new_name='vehicle_price_per_hour',
        ),
    ]
