# Generated by Django 5.2 on 2025-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_rename_vehicle_price_per_day_rent_vehicles_vehicle_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_vehicles',
            name='vehicle_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rent_vehicles',
            name='vehicle_fuel_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent_vehicles',
            name='vehicle_milage',
            field=models.IntegerField(default=0),
        ),
    ]
