# Generated by Django 5.2 on 2025-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0003_rent_vehicles_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_vehicles',
            name='vehicle_image',
            field=models.ImageField(default=1, upload_to='members/static/images/vehicle_images/'),
            preserve_default=False,
        ),
    ]
