# Generated by Django 5.2 on 2025-04-25 05:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0006_user_details_fullname_and_more'),
        ('Vehicles', '0004_rent_vehicles_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles_For_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_mileage', models.PositiveIntegerField(help_text='Enter mileage in kilometers')),
                ('used_years', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_image', models.ImageField(upload_to='vehicles_for_sale/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=20)),
                ('date_listed', models.DateTimeField(default=datetime.timezone)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Details.user_details')),
            ],
        ),
    ]
